mydata <- read.table("household_power_consumption.txt",header=TRUE,sep=";")
mydata <- subset(mydata,Date=="1/2/2007" | Date=="2/2/2007")
mydata$Global_active_power = as.numeric(as.character(mydata$Global_active_power))
hist(mydata$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)",ylab="Frequency")
axis(side=2,at=c(1200))
# dev.copy(png,"plot1.png",width=480,height=480)
# dev.off()
